version: "3"
services:
  ############################
  # manager + manager sidecar
  ############################

  manager:
    build: ./manager
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    networks:
      - hello-dapr

  manager-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 15
        window: 120s
    command: [
        "./daprd",
        "-app-id",
        "manager",
        "-app-port",
        "5000",
        "-dapr-http-port",
        "3501",
        "-components-path",
        "./components",
        "--log-level",
        "warn"
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - manager
    network_mode: "service:manager"

  ####################################################
  # notification-engine + notification-engine sidecar
  ####################################################

  notification-engine:
    build: ./notification-engine
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    networks:
      - hello-dapr

  notification-engine-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 15
        window: 120s
    command: [
        "./daprd",
        "-app-id",
        "notification-engine",
        "-app-port",
        "3000",
        "-dapr-http-port",
        "3500",
        "-components-path",
        "./components",
        "--log-level",
        "warn"
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - notification-engine
    network_mode: "service:notification-engine"

  ##########################################
  # users-accessor + users-accessor sidecar
  ##########################################
  
  users-accessor:
    build: ./users-accessor
    ports:
      - "4000:4000"
    # volumes:
    #   - .:/app
    networks:
      - hello-dapr
    links:
      - mongodb
  
  users-accessor-dapr:
    image: "daprio/daprd:edge"
    command: [
        "./daprd",
        "-app-id",
        "users-accessor",
        "-app-port",
        "4000",
        "-dapr-http-port",
        "3502",
        # "-components-path",
        # "./components",
        "--log-level",
        "warn"
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - users-accessor
    network_mode: "service:users-accessor"

  ####################################
  # news-engine + news-engine sidecar
  ####################################
  
  news-engine:
    build: ./news-engine
    ports:
      - "6000:6000"
    networks:
      - hello-dapr
  
  news-engine-dapr:
    image: "daprio/daprd:edge"
    command: [
        "./daprd",
        "-app-id",
        "news-engine",
        "-app-port",
        "6000",
        "-dapr-http-port",
        "3503",
        "--log-level",
        "warn"
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - news-engine
    network_mode: "service:news-engine"
  
  
  rabbitmq:
    image: "rabbitmq:management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hello-dapr
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - hello-dapr

networks:
  hello-dapr: null

volumes:
  data:
